type EnchantmentNames =
	| 'aqua_affinity'
	| 'bane_of_arthropods'
	| 'binding'
	| 'blast_protection'
	| 'channeling'
	| 'depth_strider'
	| 'efficiency'
	| 'feather_falling'
	| 'fire_aspect'
	| 'fire_protection'
	| 'flame'
	| 'fortune'
	| 'frost_walker'
	| 'impaling'
	| 'infinity'
	| 'knockback'
	| 'looting'
	| 'loyalty'
	| 'luck_of_the_sea'
	| 'lure'
	| 'mending'
	| 'multishot'
	| 'piercing'
	| 'power'
	| 'projectile_protection'
	| 'protection'
	| 'punch'
	| 'quick_charge'
	| 'respiration'
	| 'riptide'
	| 'sharpness'
	| 'silk_touch'
	| 'smite'
	| 'soul_speed'
	| 'swift_sneak'
	| 'thorns'
	| 'unbreaking'
	| 'vanishing';

type Structures =
	| 'ancientcity'
	| 'buriedtreasure'
	| 'endcity'
	| 'fortress'
	| 'mansion'
	| 'mineshaft'
	| 'monument'
	| 'pillageroutpost'
	| 'ruins'
	| 'shipwreck'
	| 'stronghold'
	| 'temple'
	| 'village';

type ColorPalette =
	| 'white'
	| 'light_green'
	| 'orange'
	| 'silver'
	| 'magenta'
	| 'light_blue'
	| 'yellow'
	| 'pink'
	| 'blue'
	| 'gray'
	| 'cyan'
	| 'purple'
	| 'brown'
	| 'green'
	| 'red'
	| 'black';

type Colors =
	| 'dark_red'
	| 'red'
	| 'gold'
	| 'yellow'
	| 'dark_green'
	| 'green'
	| 'aqua'
	| 'dark_aqua'
	| 'dark_blue'
	| 'blue'
	| 'light_purple'
	| 'dark_purple'
	| 'white'
	| 'gray'
	| 'dark_gray'
	| 'black'
	| 'minecoin_gold';

type PatternTypes =
	| 'base'
	| 'border'
	| 'bricks'
	| 'circle'
	| 'creeper'
	| 'cross'
	| 'curly_border'
	| 'diagonal_left'
	| 'diagonal_right'
	| 'diagonal_up_right'
	| 'diagonal_up_left'
	| 'flower'
	| 'gradient'
	| 'gradient_up'
	| 'half_horizontal'
	| 'half_horizontal_bottom'
	| 'half_vertical'
	| 'half_vertical_right'
	| 'mojang'
	| 'piglin'
	| 'rhombus'
	| 'skull'
	| 'small_stripes'
	| 'square_bottom_left'
	| 'square_bottom_right'
	| 'square_top_left'
	| 'square_top_right'
	| 'straight_cross'
	| 'stripe_bottom'
	| 'stripe_center'
	| 'stripe_downleft'
	| 'stripe_downright'
	| 'stripe_left'
	| 'stripe_middle'
	| 'stripe_right'
	| 'stripe_top'
	| 'triangle_bottom'
	| 'triangle_top'
	| 'triangles_top'
	| 'triangles_bottom';

type MusicDiscs =
	| '13'
	| 'cat'
	| 'blocks'
	| 'chirp'
	| 'far'
	| 'mall'
	| 'mellohi'
	| 'stal'
	| 'strad'
	| 'ward'
	| '11'
	| 'wait'
	| 'pigstep';

type SlotTypes =
	| 'slot.armor'
	| 'slot.armor.chest'
	| 'slot.armor.feet'
	| 'slot.armor.head'
	| 'slot.armor.legs'
	| 'slot.chest'
	| 'slot.enderchest'
	| 'slot.hotbar'
	| 'slot.inventory'
	| 'slot.saddle'
	| 'slot.weapon.mainhand'
	| 'slot.weapon.offhand'
	| 'slot.equippable';

export {
	ColorPalette,
	Colors,
	EnchantmentNames,
	MusicDiscs,
	PatternTypes,
	SlotTypes,
	Structures,
};
